### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by totordev** [chocolateimage/kdenlive_ease_generator#12]
Hey, I'm trying to use this program, but when I run the pyw file, I get this error:

kf.windowsystem: Could not find any platform plugin
Traceback (most recent call last):
  File "/home/tor/kdenlive_ease_generator/./ease_generator.pyw", line 458, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/home/tor/kdenlive_ease_generator/./ease_generator.pyw", line 293, in __init__
    self.create_easepreview()
  File "/home/tor/kdenlive_ease_generator/./ease_generator.pyw", line 385, in create_easepreview
    img = img.resize((img.width // scale, img.height // scale), resample=Image.ANTIALIAS)
                                                                         ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

Please help me

**Comment by chocolateimage** [comment]
Issue has been fixed in https://github.com/chocolateimage/kdenlive_ease_generator/commit/635ee4bdb375f64ac534b7080d731e8504125887
